export const users = [
  {
    gender: 'male',
    name: { title: 'Mr', first: 'John', last: 'Doe' },
    location: {
      street: { number: 123, name: 'Main St' },
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postcode: '10001',
      coordinates: { latitude: '40.7128', longitude: '-74.0060' },
      timezone: { offset: '-5:00', description: 'Eastern Standard Time' },
    },
    email: 'john.doe@example.com',
    login: {
      uuid: '1',
      username: 'johndoe',
      password: 'securepassword123',
      salt: 'randomsalt',
      md5: 'md5hash',
      sha1: 'sha1hash',
      sha256: 'sha256hash',
    },
    dob: { date: '1985-05-15T00:00:00Z', age: 39 },
    phone: '(555) 123-4567',
    picture: {
      large: 'https://randomuser.me/api/portraits/men/1.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/1.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/1.jpg',
    },
    favourite: false,
    tags: ['tag1', 'tag2'],
  },
  {
    gender: 'female',
    name: { title: 'Miss', first: 'Jane', last: 'Doe' },
    location: {
      street: { number: 456, name: 'Elm St' },
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      postcode: '90001',
      coordinates: { latitude: '34.0522', longitude: '-118.2437' },
      timezone: { offset: '-8:00', description: 'Pacific Standard Time' },
    },
    email: 'jane.doe@example.com',
    login: {
      uuid: '2',
      username: 'janedoe',
      password: 'securepassword456',
      salt: 'randomsalt2',
      md5: 'md5hash2',
      sha1: 'sha1hash2',
      sha256: 'sha256hash2',
    },
    dob: { date: '1990-03-10T00:00:00Z', age: 34 },
    phone: '(555) 234-5678',
    picture: {
      large: 'https://randomuser.me/api/portraits/women/2.jpg',
      medium: 'https://randomuser.me/api/portraits/med/women/2.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
    },
    favourite: false,
    tags: [],
  },
]
